In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import warnings
import seaborn as sns
from operator import attrgetter
import matplotlib.colors as mcolors
import numpy as np
import calendar


# Если файл лежит в той же папке, что и скрипт
df = pd.read_csv('data.csv')

# Посмотреть первые 5 строк
df.head()

,user_id,date,category,device,event_type,__index_level_0__
0,956977,2020-10-04 00:00:00,Office Supplies,desktop,visit,0
1,941383,2020-10-25 00:00:00,Furniture,mobile,visit,1
2,864077,2021-11-19 00:00:00,Technology,mobile,visit,2
3,689619,2022-02-05 00:00:00,Technology,desktop,visit,3
4,689619,2022-02-07 00:00:00,Technology,desktop,view,4

In [ ]:
df2 = pd.read_excel('retail.xlsx', engine='openpyxl', parse_dates=['InvoiceDate'], dtype={'CustomerID': str, 'InvoiceID': str})

df2.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom